<?php 
/* 
* Plugin Name: Captorra ID / Attorney ID
* Description: Add the Attorney ID to Gravity forms before submission. Note: The IDs in Captorra are GUIDs generated by MS CRM and can not be changed.
* Version: 0.01
*/

defined( 'ABSPATH' ) or die( 'No script kiddies please!' );

add_filter('gform_pre_render', 'add_attorney_id');
add_filter("gform_pre_submission_filter", "add_attorney_id");

function add_attorney_id( $form ) {
	
	global $wpdb;;
	
	//Get the Attorney ID
	if ( function_exists( 'get_field' ) ) {
		$aid = get_field( 'coldfusion_id' );
		if( empty( $aid ) ) {
			$aid = 'N/A';
		}
	} else {
		$aid = 'N/A';
	}
	
	
	
	foreach($form["fields"] as &$field) {
	
		//Make sure that either the admin label for the hidden field is "aid" or the field label is "Attorney ID"
		if( $field["adminLabel"] == 'aid' || $field['label'] == 'AttorneyID' || $field['label'] == 'attorney' ) {
			$field['defaultValue'] = $aid;
		}	
	
	}
	
	return $form;
}

?>